/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Lucas Thimoteo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        botaoSair1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATM");
        setBackground(new java.awt.Color(0, 255, 102));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("DEPÓSITO");
        getContentPane().add(jButton1);
        jButton1.setBounds(62, 29, 140, 47);

        jButton2.setText("PAGAMENTOS");
        getContentPane().add(jButton2);
        jButton2.setBounds(62, 94, 140, 47);

        jButton3.setText("INVESTIMENTOS");
        getContentPane().add(jButton3);
        jButton3.setBounds(62, 155, 140, 47);

        jButton7.setText("TRANSFERÊNCIAS");
        getContentPane().add(jButton7);
        jButton7.setBounds(62, 220, 140, 47);

        jButton4.setText("SAQUES");
        getContentPane().add(jButton4);
        jButton4.setBounds(413, 29, 140, 47);

        jButton5.setText("SALDO E EXTRATO");
        getContentPane().add(jButton5);
        jButton5.setBounds(413, 94, 140, 47);

        jButton6.setText("EMPRÉSTIMOS");
        getContentPane().add(jButton6);
        jButton6.setBounds(413, 155, 140, 47);

        jButton8.setText("OUTROS SERVIÇOS");
        getContentPane().add(jButton8);
        jButton8.setBounds(413, 220, 140, 47);

        botaoSair1.setText("FIM");
        botaoSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSair1ActionPerformed(evt);
            }
        });
        getContentPane().add(botaoSair1);
        botaoSair1.setBounds(480, 340, 90, 40);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDO.png"))); // NOI18N
        getContentPane().add(fundo);
        fundo.setBounds(0, 0, 600, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSair1ActionPerformed
        // TODO add your handling code here:
        BoasVindas tela = new BoasVindas();
        this.setVisible(false);
        tela.setVisible(true);
    }//GEN-LAST:event_botaoSair1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair1;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
