/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import model.Usuario;

/**
 *
 * @author Leandro
 */
public class TelaSaldoExtrato extends javax.swing.JFrame {

    Usuario usuario;
    
    public TelaSaldoExtrato() {
        initComponents();
    }
    public TelaSaldoExtrato(Usuario usuario) {
        initComponents();
        this.usuario=usuario;
//        labelSaldo.setText(usuario.getConta().getSaldo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSaldo = new javax.swing.JLabel();
        btnMostarExtrato = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        labelSaldoUsuario = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 650));

        jPanel1.setLayout(null);

        labelSaldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSaldo.setForeground(new java.awt.Color(0, 51, 102));
        labelSaldo.setText("Saldo:");
        jPanel1.add(labelSaldo);
        labelSaldo.setBounds(50, 200, 70, 50);

        btnMostarExtrato.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMostarExtrato.setForeground(new java.awt.Color(0, 51, 102));
        btnMostarExtrato.setText("Mostrar Extrato");
        jPanel1.add(btnMostarExtrato);
        btnMostarExtrato.setBounds(300, 500, 200, 50);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LOGO.png"))); // NOI18N
        jPanel1.add(labelLogo);
        labelLogo.setBounds(50, 50, 250, 100);

        labelSaldoUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelSaldoUsuario.setForeground(new java.awt.Color(0, 102, 153));
        labelSaldoUsuario.setText("Saldo do Usuario");
        jPanel1.add(labelSaldoUsuario);
        labelSaldoUsuario.setBounds(130, 200, 310, 50);

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(102, 0, 51));
        btnVoltar.setText("Voltar");
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(550, 500, 200, 50);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDO.png"))); // NOI18N
        jPanel1.add(labelFundo);
        labelFundo.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaldoExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaldoExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaldoExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaldoExtrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaldoExtrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostarExtrato;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelSaldoUsuario;
    // End of variables declaration//GEN-END:variables
}
