/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author Leandro
 */
public class TelaBemVindoMenu extends javax.swing.JFrame {

   Usuario usuario;
   
    public TelaBemVindoMenu() {
        initComponents();
      
    }
    public TelaBemVindoMenu(Usuario usuario) {
        initComponents();
        this.usuario=usuario;
        labelNomeUsuario.setText(usuario.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        labelNomeUsuario = new javax.swing.JLabel();
        labelBemVindo = new javax.swing.JLabel();
        btnFim = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnOutrosServicos = new javax.swing.JButton();
        btnTransferencias = new javax.swing.JButton();
        btnInvestimentos = new javax.swing.JButton();
        btnPagamentos = new javax.swing.JButton();
        btnSaques = new javax.swing.JButton();
        btnSaldoExtrato = new javax.swing.JButton();
        btnEmprestimos = new javax.swing.JButton();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(820, 650));

        painelPrincipal.setLayout(null);

        labelNomeUsuario.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        labelNomeUsuario.setText("Nome do Usuario");
        painelPrincipal.add(labelNomeUsuario);
        labelNomeUsuario.setBounds(200, 40, 350, 30);

        labelBemVindo.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        labelBemVindo.setText("Bem Vindo, ");
        painelPrincipal.add(labelBemVindo);
        labelBemVindo.setBounds(54, 44, 140, 30);

        btnFim.setText("FIM");
        btnFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFimActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnFim);
        btnFim.setBounds(360, 470, 120, 40);

        btnDeposito.setText("DEPÓSITO");
        painelPrincipal.add(btnDeposito);
        btnDeposito.setBounds(120, 160, 220, 47);

        btnOutrosServicos.setText("OUTROS SERVIÇOS");
        painelPrincipal.add(btnOutrosServicos);
        btnOutrosServicos.setBounds(480, 350, 230, 47);

        btnTransferencias.setText("TRANSFERÊNCIAS");
        painelPrincipal.add(btnTransferencias);
        btnTransferencias.setBounds(120, 350, 220, 47);

        btnInvestimentos.setText("INVESTIMENTOS");
        painelPrincipal.add(btnInvestimentos);
        btnInvestimentos.setBounds(120, 280, 220, 47);

        btnPagamentos.setText("PAGAMENTOS");
        painelPrincipal.add(btnPagamentos);
        btnPagamentos.setBounds(120, 220, 220, 47);

        btnSaques.setText("SAQUES");
        painelPrincipal.add(btnSaques);
        btnSaques.setBounds(480, 160, 230, 47);

        btnSaldoExtrato.setText("SALDO E EXTRATO");
        btnSaldoExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoExtratoActionPerformed(evt);
            }
        });
        painelPrincipal.add(btnSaldoExtrato);
        btnSaldoExtrato.setBounds(480, 220, 230, 47);

        btnEmprestimos.setText("EMPRÉSTIMOS");
        painelPrincipal.add(btnEmprestimos);
        btnEmprestimos.setBounds(480, 280, 230, 47);

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FUNDOresize.png"))); // NOI18N
        labelFundo.setText("jLabel2");
        painelPrincipal.add(labelFundo);
        labelFundo.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFimActionPerformed
        int a =JOptionPane.showConfirmDialog(painelPrincipal, "Tem certeza que quer sair");
        if(a==0)
            this.dispose();
    }//GEN-LAST:event_btnFimActionPerformed

    private void btnSaldoExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoExtratoActionPerformed
       this.setVisible(false);
       new TelaSaldoExtrato(usuario).setVisible(true);
    }//GEN-LAST:event_btnSaldoExtratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBemVindoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBemVindoMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnEmprestimos;
    private javax.swing.JButton btnFim;
    private javax.swing.JButton btnInvestimentos;
    private javax.swing.JButton btnOutrosServicos;
    private javax.swing.JButton btnPagamentos;
    private javax.swing.JButton btnSaldoExtrato;
    private javax.swing.JButton btnSaques;
    private javax.swing.JButton btnTransferencias;
    private javax.swing.JLabel labelBemVindo;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelNomeUsuario;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
